version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/xandr"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/xandr/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/xandr_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/xandr_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/xandr_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" 
    directory: "/packages/xandr_android/android" 
    schedule:
      interval: "daily"
  - package-ecosystem: "swift" 
    directory: "/packages/xandr_ios/ios" 
    schedule:
      interval: "daily"